services:
  webserver:
    image: php:apache
    container_name: webserver
    build: ./docker/php
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:80'
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=purrfect_db
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
      - TZ=America/Sao_Paulo
    ports:
      - '3307:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-strict-mode=true
volumes:
  mysql-volume:
    driver: local

