services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=purrfect_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
volumes:
  mysql-volume:
    driver: local